task_creation_form.simple_form:
  path: '/tasks/{tasks}/time'
  defaults:
    _form:  '\Drupal\tasks\Form\TimeSpent'
    _title: 'Enter time you spent for this task'
  requirements:
    _permission: 'access content'
  options:
    parameters:
      tasks:
        type: entity:tasks_manager
